### ISSUE TITLE
Routes precedence sanitisation removes all routes except one

### ISSUE THREAD

**Issue by activehigh** [monimesl/istio-virtualservice-merger#8]
Current routes precedence sanitization is broken. It removes routes except the first one. A summary is given below -

## Setup
My setup for testing  -

Virtual Service -
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: integration-test
spec:
  gateways:
    - "mesh"
  hosts:
    - "integration.test.com"
  http:
    - timeout: 5s
      route:
        - destination:
            host: "integration.test.com"
```

Virtual Service Merge 1 -
```yaml
apiVersion: istiomerger.monime.sl/v1alpha1
kind: VirtualServiceMerge
metadata:
  name: review-routes
spec:
  target:
    name: "integration-test"
  patch:
    http:
      - match:
          - uri:
              prefix: "/reviews"
        route:
          - destination:
              port:
                number: 8080
              host: "review-service"
```

Virtual Service Merge 2 -
```yaml
apiVersion: istiomerger.monime.sl/v1alpha1
kind: VirtualServiceMerge
metadata:
  name: product-routes
spec:
  target:
    name: "integration-test"
  patch:
    http:
      - match:
          - uri:
              prefix: "/products"
        route:
          - destination:
              port:
                number: 8080
              host: "product-service"
```
## What you expect
These are different VirtualServiceMerge objects with unique routes. So precedence should not worry about it and just add both routes to the virtual service object.
## What happens
The controller drops the second route because the routes generator always appends to the end of the route - 
```
2022-08-25T09:59:52.821+1000	INFO	istio-virtualservice-merger	[Start] Reconciliation	{"Request.Namespace": "istio-virtualservice-merger", "Request.Name": "product-routes"}
2022-08-25T09:59:53.692+1000	INFO	istio-virtualservice-merger	Dropping the duplicate route name prefix	{"prefix": "0", "route": "product-routes-0"}
2022-08-25T09:59:53.729+1000	INFO	istio-virtualservice-merger	[Complete] Reconciliation	{"Request.Namespace": "istio-virtualservice-merger/product-routes", "Request.Name": "product-routes"}
```

Even if you add a suffix it does not work. I added a suffix as `1` and `2` in diff routes and I get this -
```
2022-08-25T10:32:25.586+1000	INFO	istio-virtualservice-merger	[Start] Reconciliation	{"Request.Namespace": "istio-virtualservice-merger", "Request.Name": "product-routes-1"}
2022-08-25T10:32:25.589+1000	INFO	istio-virtualservice-merger	Dropping the duplicate route name prefix	{"prefix": "0", "route": "product-routes-1-0"}
2022-08-25T10:32:25.603+1000	INFO	istio-virtualservice-merger	[Complete] Reconciliation	{"Request.Namespace": "istio-virtualservice-merger/product-routes-1", "Request.Name": "product-routes-1"}
```
It always adds a trailing `0` and then drop all the routes

## Reason for this to happen
Since each virtual service merge is an individual object, both route gets a suffix of `-0` at the end of it. But the sanitization logic only allows one index due to precedence check. So it wrongly removes `product-routes-0` even though this is unique and does not have a relation with `review-routes-0`

## Possible Resolve
Need to fix the precedence check logic only to apply if the route prefix matches, so in addition to checking the index it will also check whether the prefix matches or not. In a proper situation, `review-routes-0` and `product-routes-0` both will be added.

**Comment by alphashaw** [comment]
Hello @activehigh  .

The [parsePrecedence](https://github.com/monimesl/istio-virtualservice-merger/blob/9355a9e78e36aad9f0d665b1e868a11860356f0f/api/v1alpha1/virtualservicemerge_types.go#L198-L211) function was returning the precedence as the  prefix, this was causing the duplication scenarios.
Cases where the route name was explicitly set in the patch, this issue won't occur.
It will be much safer to explicitly set the route name in patch rather than relying on the operator to generate it from the name of the Merge object and index of the route in the spec.

For precedence to kick-in, the full route name must be of the format _**routeName-predendeceNumber**_
